language: go

before_deploy:
  - go build -o ./organicbot github.com/cdorsey/organicbot

deploy:
  skip_cleanup: true
  provider: script
  script: sh ./deploy.sh
  on:
    branch: ci-testing

addons:
  ssh_known_hosts: chase-dorsey.com

notifications:
  email: false