language: go

before_deploy:
  - go build -o ./organicbot $GOPATH/src/github.com/cdorsey/organicbot

after_install:
  - pwd
  - ls

deploy:
  skip_cleanup: true
  provider: script
  script: sh ./deploy.sh
  on:
    branch: ci-testing

addons:
  ssh_known_hosts: chase-dorsey.com